# Generated by Django 5.2.7 on 2026-09-17 14:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connector', '0001_initial'),
        ('partner', '0003_credentialscope_partnerapplication_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CanonicalTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_event_id', models.CharField(max_length=255)),
                ('source_account_reference', models.CharField(max_length=255)),
                ('direction', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=10)),
                ('transaction_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('POSTED', 'Posted'), ('REVERSED', 'Reversed'), ('FAILED', 'Failed')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(max_length=3)),
                ('occurred_at', models.DateTimeField()),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('counterparty_name', models.CharField(blank=True, max_length=255)),
                ('counterparty_reference', models.CharField(blank=True, max_length=255)),
                ('channel', models.CharField(blank=True, max_length=100)),
                ('merchant_category', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('source_provenance', models.JSONField(default=dict)),
                ('normalisation_version', models.CharField(max_length=50)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canonical_transactions', to='connector.institutionconnection')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canonical_transactions', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canonical_transactions', to='partner.institution')),
                ('raw_event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='canonical_transaction', to='connector.rawevent')),
            ],
            options={
                'indexes': [models.Index(fields=['institution', 'occurred_at'], name='normalisati_institu_dcb415_idx'), models.Index(fields=['connection', 'source_event_id'], name='normalisati_connect_a15de8_idx'), models.Index(fields=['institution', 'status'], name='normalisati_institu_5810ac_idx')],
            },
        ),
    ]
