# Generated by Django 5.2.7 on 2026-09-14 00:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_permission_remove_serviceaccount_is_active_and_more'),
        ('partner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='institutionmembership',
            name='partner_ins_institu_9d4f9f_idx',
        ),
        migrations.RemoveField(
            model_name='institutionmembership',
            name='is_active',
        ),
        migrations.AddField(
            model_name='institutionmembership',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='memberships', to='identity.role'),
        ),
        migrations.AddField(
            model_name='institutionmembership',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('ENDED', 'Ended')], db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='institutionmembership',
            name='role',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='institutionmembership',
            index=models.Index(fields=['institution', 'status'], name='partner_ins_institu_5b8cee_idx'),
        ),
    ]
