# Generated by Django 5.2.7 on 2026-09-17 03:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_permission_remove_serviceaccount_is_active_and_more'),
        ('partner', '0002_remove_institutionmembership_partner_ins_institu_9d4f9f_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialScope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartnerApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('REVOKED', 'Revoked')], db_index=True, default='ACTIVE', max_length=20)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partner_applications', to='partner.institution')),
                ('service_account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='partner_application', to='identity.serviceaccount')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerEnvironment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('SANDBOX', 'Sandbox'), ('STAGING', 'Staging'), ('PRODUCTION', 'Production')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISABLED', 'Disabled')], db_index=True, default='ACTIVE', max_length=20)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='environments', to='partner.partnerapplication')),
            ],
        ),
        migrations.CreateModel(
            name='ApiCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('client_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('secret_digest', models.CharField(editable=False, max_length=64)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked')], db_index=True, default='ACTIVE', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_credentials', to=settings.AUTH_USER_MODEL)),
                ('rotated_from', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rotated_to', to='partner.apicredential')),
                ('scopes', models.ManyToManyField(related_name='api_credentials', to='partner.credentialscope')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='api_credentials', to='partner.partnerenvironment')),
            ],
        ),
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(max_length=500)),
                ('event_types', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISABLED', 'Disabled')], db_index=True, default='ACTIVE', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='webhook_endpoints', to='partner.partnerenvironment')),
            ],
        ),
        migrations.AddIndex(
            model_name='partnerapplication',
            index=models.Index(fields=['institution', 'status'], name='partner_par_institu_37d974_idx'),
        ),
        migrations.AddConstraint(
            model_name='partnerapplication',
            constraint=models.UniqueConstraint(fields=('institution', 'slug'), name='unique_partner_application_slug_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='partnerenvironment',
            index=models.Index(fields=['application', 'status'], name='partner_par_applica_47da70_idx'),
        ),
        migrations.AddConstraint(
            model_name='partnerenvironment',
            constraint=models.UniqueConstraint(fields=('application', 'kind'), name='unique_partner_application_environment'),
        ),
        migrations.AddIndex(
            model_name='apicredential',
            index=models.Index(fields=['environment', 'status'], name='partner_api_environ_1332b9_idx'),
        ),
        migrations.AddConstraint(
            model_name='apicredential',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('revoked_at__isnull', False), ('status', 'REVOKED')), models.Q(('status', 'ACTIVE'), ('revoked_at__isnull', True)), _connector='OR'), name='api_credential_revocation_matches_status'),
        ),
        migrations.AddIndex(
            model_name='webhookendpoint',
            index=models.Index(fields=['environment', 'status'], name='partner_web_environ_b6d99a_idx'),
        ),
        migrations.AddConstraint(
            model_name='webhookendpoint',
            constraint=models.UniqueConstraint(fields=('environment', 'url'), name='unique_webhook_url_per_environment'),
        ),
        migrations.RunSQL(
            sql="""
                CREATE FUNCTION tamva_protect_api_credential_identity()
                RETURNS trigger AS $$
                BEGIN
                    IF NEW.client_id IS DISTINCT FROM OLD.client_id
                       OR NEW.secret_digest IS DISTINCT FROM OLD.secret_digest THEN
                        RAISE EXCEPTION 'API credential identity is immutable'
                            USING ERRCODE = 'integrity_constraint_violation';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER api_credential_identity_is_immutable
                BEFORE UPDATE ON partner_apicredential
                FOR EACH ROW EXECUTE FUNCTION tamva_protect_api_credential_identity();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS api_credential_identity_is_immutable
                    ON partner_apicredential;
                DROP FUNCTION IF EXISTS tamva_protect_api_credential_identity();
            """,
        ),
    ]
