# Generated by Django 5.2.7 on 2026-09-19 00:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0003_credentialscope_partnerapplication_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionLocaleSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country_code', models.CharField(default='GH', max_length=2)),
                ('default_currency', models.CharField(default='GHS', max_length=3)),
                ('timezone', models.CharField(default='Africa/Accra', max_length=64)),
                ('locale', models.CharField(default='en-GH', max_length=20)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='locale_settings', to='partner.institution')),
            ],
            options={
                'verbose_name_plural': 'institution locale settings',
            },
        ),
    ]
