# Generated by Django 5.2.7 on 2026-09-17 15:52

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0001_initial'),
        ('partner', '0003_credentialscope_partnerapplication_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_profiles', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_profiles', to='partner.institution')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialProfileSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('computation_version', models.CharField(max_length=50)),
                ('source_fingerprint', models.CharField(max_length=64)),
                ('account_count', models.PositiveIntegerField(default=0)),
                ('covered_account_count', models.PositiveIntegerField(default=0)),
                ('coverage_ratio', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=5)),
                ('confidence', models.CharField(default='LOW', max_length=20)),
                ('completeness', models.JSONField(default=dict)),
                ('provenance', models.JSONField(default=dict)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='profile.financialprofile')),
            ],
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='current_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_profiles', to='profile.financialprofilesnapshot'),
        ),
        migrations.CreateModel(
            name='ExpenseSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('observation_count', models.PositiveIntegerField(default=0)),
                ('by_category', models.JSONField(default=dict)),
                ('snapshot', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='profile.financialprofilesnapshot')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CashFlowSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_inflows', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('total_outflows', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('net_cash_flow', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('transaction_count', models.PositiveIntegerField(default=0)),
                ('snapshot', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cash_flow', to='profile.financialprofilesnapshot')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=3)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('period_inflows', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('period_outflows', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('entry_count', models.PositiveIntegerField(default=0)),
                ('covered', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profile_summaries', to='ledger.account')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_summaries', to='profile.financialprofilesnapshot')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estimated_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('observation_count', models.PositiveIntegerField(default=0)),
                ('methodology', models.CharField(default='credit_flow', max_length=100)),
                ('snapshot', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='income', to='profile.financialprofilesnapshot')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileComputationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('computation_version', models.CharField(max_length=50)),
                ('source_fingerprint', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('REUSED', 'Reused'), ('FAILED', 'Failed')], db_index=True, default='RUNNING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='computation_runs', to='profile.financialprofile')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='computation_runs', to='profile.financialprofilesnapshot')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SavingsSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('net_savings', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('savings_rate', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=7)),
                ('methodology', models.CharField(default='net_cash_flow_ratio', max_length=100)),
                ('snapshot', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='savings', to='profile.financialprofilesnapshot')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='financialprofilesnapshot',
            index=models.Index(fields=['profile', 'is_current', 'period_end'], name='profile_fin_profile_d9076b_idx'),
        ),
        migrations.AddConstraint(
            model_name='financialprofilesnapshot',
            constraint=models.UniqueConstraint(fields=('profile', 'period_start', 'period_end', 'computation_version', 'source_fingerprint'), name='unique_profile_snapshot_input'),
        ),
        migrations.AddConstraint(
            model_name='financialprofile',
            constraint=models.UniqueConstraint(fields=('institution', 'customer'), name='unique_financial_profile_per_customer'),
        ),
        migrations.AddConstraint(
            model_name='accountsummary',
            constraint=models.UniqueConstraint(fields=('snapshot', 'account'), name='unique_snapshot_account_summary'),
        ),
    ]
