# Generated by Django 5.2.7 on 2026-09-17 13:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partner', '0003_credentialscope_partnerapplication_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectorDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('version', models.CharField(default='1', max_length=50)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISABLED', 'Disabled')], db_index=True, default='ACTIVE', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstitutionConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_reference', models.CharField(max_length=200)),
                ('purpose_code', models.SlugField(max_length=100)),
                ('scope_code', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('REVOKED', 'Revoked'), ('FAILED', 'Failed')], db_index=True, default='ACTIVE', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='institution_connections', to='connector.connectordefinition')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='institution_connections', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='connector_connections', to='partner.institution')),
            ],
        ),
        migrations.CreateModel(
            name='ConnectorSyncRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying')], db_index=True, default='RUNNING', max_length=20)),
                ('cursor', models.CharField(blank=True, max_length=500)),
                ('next_cursor', models.CharField(blank=True, max_length=500)),
                ('attempt', models.PositiveIntegerField(default=1)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('retryable', models.BooleanField(default=False)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_count', models.PositiveIntegerField(default=0)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('quarantined_count', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sync_runs', to='connector.institutionconnection')),
            ],
        ),
        migrations.CreateModel(
            name='ConnectorCredentialReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=255)),
                ('credential_type', models.CharField(default='provider_reference', max_length=100)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='credential_reference', to='connector.institutionconnection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RawEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_event_id', models.CharField(blank=True, max_length=255)),
                ('deduplication_key', models.CharField(max_length=128)),
                ('payload', models.JSONField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('provenance', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('READY_FOR_NORMALISATION', 'Ready for normalisation'), ('QUARANTINED', 'Quarantined')], db_index=True, max_length=40)),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_events', to='connector.institutionconnection')),
                ('sync_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_events', to='connector.connectorsyncrun')),
            ],
        ),
        migrations.CreateModel(
            name='QuarantineEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason_code', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RELEASED', 'Released'), ('DISCARDED', 'Discarded')], db_index=True, default='OPEN', max_length=20)),
                ('quarantined_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('raw_event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='quarantine_event', to='connector.rawevent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IngestionError',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('retryable', models.BooleanField(default=False)),
                ('attempt', models.PositiveIntegerField(default=1)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('sync_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingestion_errors', to='connector.connectorsyncrun')),
                ('raw_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingestion_errors', to='connector.rawevent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='institutionconnection',
            index=models.Index(fields=['institution', 'status'], name='connector_i_institu_0b89cd_idx'),
        ),
        migrations.AddConstraint(
            model_name='institutionconnection',
            constraint=models.UniqueConstraint(fields=('institution', 'connector', 'external_reference'), name='unique_connection_per_institution_provider_reference'),
        ),
        migrations.AddIndex(
            model_name='connectorsyncrun',
            index=models.Index(fields=['connection', 'status'], name='connector_c_connect_1d891f_idx'),
        ),
        migrations.AddIndex(
            model_name='rawevent',
            index=models.Index(fields=['connection', 'status'], name='connector_r_connect_00de3e_idx'),
        ),
        migrations.AddConstraint(
            model_name='rawevent',
            constraint=models.UniqueConstraint(fields=('connection', 'deduplication_key'), name='unique_raw_event_deduplication_key'),
        ),
        migrations.AddConstraint(
            model_name='rawevent',
            constraint=models.UniqueConstraint(condition=models.Q(('source_event_id', ''), _negated=True), fields=('connection', 'source_event_id'), name='unique_raw_event_source_id'),
        ),
    ]
