# Generated by Django 5.2.7 on 2026-09-18 06:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feature', '0001_initial'),
        ('partner', '0003_credentialscope_partnerapplication_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('model_type', models.CharField(max_length=50)),
                ('owner_scope', models.CharField(choices=[('PLATFORM', 'Platform'), ('INSTITUTION', 'Institution')], default='PLATFORM', max_length=20)),
                ('score_min', models.DecimalField(decimal_places=4, max_digits=10)),
                ('score_max', models.DecimalField(decimal_places=4, max_digits=10)),
                ('score_direction', models.CharField(choices=[('HIGHER_IS_RISKIER', 'Higher is riskier'), ('HIGHER_IS_SAFER', 'Higher is safer')], max_length=20)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='model_definitions', to='partner.institution')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('RETIRED', 'Retired')], default='DRAFT', max_length=20)),
                ('provider_code', models.CharField(max_length=100)),
                ('input_contract_version', models.CharField(max_length=50)),
                ('output_contract_version', models.CharField(max_length=50)),
                ('artifact_reference', models.JSONField(blank=True, default=dict)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('model_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='modeling.modeldefinition')),
            ],
        ),
        migrations.CreateModel(
            name='ModelFeatureBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('required', models.BooleanField(default=True)),
                ('expected_type', models.CharField(choices=[('DECIMAL', 'Decimal'), ('BOOLEAN', 'Boolean'), ('CATEGORICAL', 'Categorical')], max_length=20)),
                ('on_missing', models.CharField(choices=[('OMIT', 'Omit from input'), ('DEFAULT', 'Use configured default'), ('FAIL', 'Fail the evaluation')], default='OMIT', max_length=20)),
                ('default_value', models.JSONField(blank=True, null=True)),
                ('transformation', models.JSONField(blank=True, default=dict)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_bindings', to='feature.featuredefinition')),
                ('model_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feature_bindings', to='modeling.modelversion')),
            ],
            options={
                'ordering': ['feature__code'],
            },
        ),
        migrations.CreateModel(
            name='ModelEvaluationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_fingerprint', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_evaluation_runs', to=settings.AUTH_USER_MODEL)),
                ('feature_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_evaluation_runs', to='feature.featurecomputationrun')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_evaluation_runs', to='partner.institution')),
                ('model_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_runs', to='modeling.modelversion')),
            ],
        ),
        migrations.CreateModel(
            name='ModelEvaluationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(decimal_places=4, max_digits=10)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('output_code', models.CharField(blank=True, max_length=100)),
                ('contributions', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='result', to='modeling.modelevaluationrun')),
                ('model_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='modeling.modelversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='modelversion',
            constraint=models.UniqueConstraint(fields=('model_definition', 'version'), name='unique_model_version'),
        ),
        migrations.AddConstraint(
            model_name='modelfeaturebinding',
            constraint=models.UniqueConstraint(fields=('model_version', 'feature'), name='unique_model_feature_binding'),
        ),
        migrations.AddConstraint(
            model_name='modelevaluationrun',
            constraint=models.UniqueConstraint(fields=('feature_run', 'model_version', 'source_fingerprint'), name='unique_model_evaluation_input'),
        ),
    ]
