# Generated by Django 5.2.7 on 2026-09-18 06:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feature', '0001_initial'),
        ('partner', '0003_credentialscope_partnerapplication_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('operator', models.CharField(choices=[('EQ', 'Equals'), ('NE', 'Not equals'), ('GT', 'Greater than'), ('GTE', 'Greater than or equal'), ('LT', 'Less than'), ('LTE', 'Less than or equal'), ('BETWEEN', 'Between'), ('IN', 'In'), ('NOT_IN', 'Not in'), ('EXISTS', 'Exists'), ('NOT_EXISTS', 'Not exists')], max_length=20)),
                ('threshold', models.JSONField(default=dict)),
                ('severity', models.CharField(default='INFO', max_length=30)),
                ('reason_code', models.CharField(max_length=100)),
                ('version', models.CharField(default='1', max_length=50)),
                ('missing_policy', models.CharField(choices=[('SKIP', 'Skip'), ('FAIL_CLOSED', 'Fail closed'), ('FAIL_OPEN', 'Fail open')], default='SKIP', max_length=20)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='feature.featuredefinition')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RuleSetMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordinal', models.PositiveIntegerField(default=0)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rules.ruledefinition')),
            ],
            options={
                'ordering': ['ordinal', 'rule__code'],
            },
        ),
        migrations.CreateModel(
            name='RuleSetVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('RETIRED', 'Retired')], default='DRAFT', max_length=20)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('rules', models.ManyToManyField(through='rules.RuleSetMembership', to='rules.ruledefinition')),
            ],
        ),
        migrations.AddField(
            model_name='rulesetmembership',
            name='rule_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rules.rulesetversion'),
        ),
        migrations.CreateModel(
            name='RuleEvaluationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_fingerprint', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('REUSED', 'Reused')], default='RUNNING', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rule_evaluation_runs', to=settings.AUTH_USER_MODEL)),
                ('feature_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rule_runs', to='feature.featurecomputationrun')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rule_evaluation_runs', to='partner.institution')),
                ('rule_set_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_runs', to='rules.rulesetversion')),
            ],
        ),
        migrations.CreateModel(
            name='RuleEvaluationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matched', models.BooleanField(blank=True, null=True)),
                ('skipped', models.BooleanField(default=False)),
                ('observed_value', models.JSONField(blank=True, null=True)),
                ('expected_value', models.JSONField(blank=True, default=dict)),
                ('reason_code', models.CharField(max_length=100)),
                ('severity', models.CharField(max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='rules.ruledefinition')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='rules.ruleevaluationrun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('run', 'rule'), name='unique_rule_evaluation_result')],
            },
        ),
        migrations.AddConstraint(
            model_name='rulesetversion',
            constraint=models.UniqueConstraint(fields=('code', 'version'), name='unique_rule_set_version'),
        ),
        migrations.AddConstraint(
            model_name='rulesetmembership',
            constraint=models.UniqueConstraint(fields=('rule_set', 'rule'), name='unique_rule_set_rule'),
        ),
        migrations.AddConstraint(
            model_name='ruleevaluationrun',
            constraint=models.UniqueConstraint(fields=('feature_run', 'rule_set_version', 'source_fingerprint'), name='unique_rule_evaluation_input'),
        ),
    ]
