# Generated by Django 5.2.7 on 2026-09-16 23:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partner', '0002_remove_institutionmembership_partner_ins_institu_9d4f9f_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentScope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsentPurpose',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consent_purposes', to='partner.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('GRANTED', 'Granted'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], db_index=True, default='GRANTED', max_length=20)),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_consents', to='partner.institution')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents', to='consent.consentpurpose')),
                ('scopes', models.ManyToManyField(related_name='consents', to='consent.consentscope')),
            ],
        ),
        migrations.CreateModel(
            name='ConsentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('GRANTED', 'Granted'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], db_index=True, max_length=20)),
                ('snapshot', models.JSONField(default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_events', to=settings.AUTH_USER_MODEL)),
                ('consent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='consent.consent')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consent_events', to='partner.institution')),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
                'indexes': [models.Index(fields=['institution', 'occurred_at'], name='consent_con_institu_ca2066_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='consentpurpose',
            index=models.Index(fields=['institution', 'is_active'], name='consent_con_institu_edc063_idx'),
        ),
        migrations.AddConstraint(
            model_name='consentpurpose',
            constraint=models.UniqueConstraint(fields=('institution', 'code'), name='unique_consent_purpose_per_institution'),
        ),
        migrations.AddIndex(
            model_name='consent',
            index=models.Index(fields=['institution', 'customer', 'status'], name='consent_con_institu_6b1784_idx'),
        ),
        migrations.AddIndex(
            model_name='consent',
            index=models.Index(fields=['expires_at', 'status'], name='consent_con_expires_972263_idx'),
        ),
        migrations.AddConstraint(
            model_name='consent',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('granted_at'))), name='consent_expiry_after_grant'),
        ),
        migrations.AddConstraint(
            model_name='consent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('revoked_at__isnull', False), ('status', 'REVOKED')), models.Q(models.Q(('status', 'REVOKED'), _negated=True), ('revoked_at__isnull', True)), _connector='OR'), name='consent_revocation_timestamp_matches_status'),
        ),
        migrations.RunSQL(
            sql="""
                CREATE FUNCTION tamva_prevent_consent_event_mutation()
                RETURNS trigger AS $$
                BEGIN
                    RAISE EXCEPTION 'consent events are immutable'
                        USING ERRCODE = 'integrity_constraint_violation';
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER consent_events_are_immutable
                BEFORE UPDATE OR DELETE ON consent_consentevent
                FOR EACH ROW EXECUTE FUNCTION tamva_prevent_consent_event_mutation();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS consent_events_are_immutable
                    ON consent_consentevent;
                DROP FUNCTION IF EXISTS tamva_prevent_consent_event_mutation();
            """,
        ),
    ]
