# Generated by Django 5.2.7 on 2026-09-18 15:01

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partner', '0003_credentialscope_partnerapplication_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterpartyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counterparty_reference', models.CharField(max_length=255)),
                ('counterparty_name', models.CharField(blank=True, max_length=255)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('transaction_count', models.PositiveIntegerField(default=0)),
                ('total_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counterparty_profiles', to='partner.institution')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerCounterpartyRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('transaction_count', models.PositiveIntegerField(default=0)),
                ('inbound_count', models.PositiveIntegerField(default=0)),
                ('outbound_count', models.PositiveIntegerField(default=0)),
                ('total_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('average_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_relationships', to='counterparty.counterpartyprofile')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counterparty_relationships', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counterparty_relationships', to='partner.institution')),
            ],
        ),
        migrations.CreateModel(
            name='CounterpartyObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('occurred_at', models.DateTimeField()),
                ('provenance_type', models.CharField(max_length=100)),
                ('provenance_id', models.UUIDField()),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='counterparty.customercounterpartyrelationship')),
            ],
            options={
                'ordering': ['occurred_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='counterpartyprofile',
            constraint=models.UniqueConstraint(fields=('institution', 'counterparty_reference'), name='unique_counterparty_profile'),
        ),
        migrations.AddIndex(
            model_name='customercounterpartyrelationship',
            index=models.Index(fields=['institution', 'customer'], name='counterpart_institu_96a42b_idx'),
        ),
        migrations.AddConstraint(
            model_name='customercounterpartyrelationship',
            constraint=models.UniqueConstraint(fields=('customer', 'counterparty'), name='unique_customer_counterparty'),
        ),
        migrations.AddConstraint(
            model_name='counterpartyobservation',
            constraint=models.UniqueConstraint(fields=('relationship', 'provenance_type', 'provenance_id'), name='unique_counterparty_observation'),
        ),
    ]
