# Generated by Django 5.2.7 on 2026-09-19 00:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partner', '0004_institutionlocalesettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource_type', models.CharField(choices=[('RISK_EVENTS', 'Risk events'), ('CASES', 'Cases'), ('CUSTOMERS', 'Customers'), ('NOTIFICATIONS', 'Notifications'), ('SECURITY_EVENTS', 'Security events'), ('AUDIT_EVENTS', 'Audit events')], max_length=30)),
                ('format', models.CharField(choices=[('CSV', 'CSV'), ('XLSX', 'XLSX')], max_length=10)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('ordering', models.CharField(blank=True, max_length=200)),
                ('columns', models.JSONField(default=list)),
                ('selected_ids', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=20)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('artifact', models.FileField(blank=True, max_length=255, upload_to='exports/')),
                ('artifact_size', models.PositiveBigIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='export_jobs', to='partner.institution')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='export_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['institution', 'requested_by', 'created_at'], name='operations__institu_f0daf0_idx'), models.Index(fields=['status', 'expires_at'], name='operations__status_b24852_idx')],
            },
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=128)),
                ('request_hash', models.CharField(max_length=64)),
                ('response', models.JSONField()),
                ('status_code', models.PositiveSmallIntegerField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_records', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_records', to='partner.institution')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('actor', 'institution', 'endpoint', 'key'), name='unique_idempotency_key_per_actor_endpoint')],
            },
        ),
        migrations.CreateModel(
            name='SavedView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource_type', models.CharField(choices=[('RISK_EVENTS', 'Risk events'), ('CASES', 'Cases'), ('CUSTOMERS', 'Customers'), ('NOTIFICATIONS', 'Notifications'), ('SECURITY_EVENTS', 'Security events'), ('AUDIT_EVENTS', 'Audit events')], max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('ordering', models.CharField(blank=True, max_length=200)),
                ('visible_columns', models.JSONField(blank=True, default=list)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_views', to='partner.institution')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['institution', 'owner', 'resource_type'], name='operations__institu_c4a38a_idx')],
                'constraints': [models.UniqueConstraint(fields=('institution', 'owner', 'resource_type', 'name'), name='unique_saved_view_name_per_owner_resource')],
            },
        ),
    ]
