# Generated by Django 5.2.7 on 2026-09-18 12:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partner', '0003_credentialscope_partnerapplication_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialPassport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_passports', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_passports', to='partner.institution')),
            ],
        ),
        migrations.CreateModel(
            name='PassportShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose_code', models.CharField(max_length=100)),
                ('allowed_sections', models.JSONField(default=list)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passport_shares_created', to=settings.AUTH_USER_MODEL)),
                ('recipient_institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_passport_shares', to='partner.institution')),
            ],
        ),
        migrations.CreateModel(
            name='PassportShareAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('outcome', models.CharField(choices=[('SUCCESS', 'Success'), ('DENIED', 'Denied')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=100)),
                ('requested_sections', models.JSONField(default=list)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('accessor_institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passport_share_accesses', to='partner.institution')),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accesses', to='passport.passportshare')),
            ],
            options={
                'ordering': ['accessed_at'],
            },
        ),
        migrations.CreateModel(
            name='PassportSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schema_version', models.CharField(max_length=20)),
                ('source_fingerprint', models.CharField(max_length=64)),
                ('provenance', models.JSONField(default=dict)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('passport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='passport.financialpassport')),
            ],
        ),
        migrations.AddField(
            model_name='passportshare',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shares', to='passport.passportsnapshot'),
        ),
        migrations.CreateModel(
            name='PassportSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('IDENTITY', 'Identity'), ('FINANCIAL_SUMMARY', 'Financial summary'), ('INCOME_SUMMARY', 'Income summary'), ('CASHFLOW_SUMMARY', 'Cashflow summary'), ('SAVINGS_SUMMARY', 'Savings summary'), ('ACCOUNT_COVERAGE', 'Account coverage'), ('PROFILE_COMPLETENESS', 'Profile completeness'), ('SELECTED_TRUST_SIGNALS', 'Selected trust signals'), ('SELECTED_RISK_SUMMARY', 'Selected risk summary'), ('NETWORK_SUMMARY', 'Network summary')], max_length=30)),
                ('schema_version', models.CharField(max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='passport.passportsnapshot')),
            ],
        ),
        migrations.AddField(
            model_name='financialpassport',
            name='current_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_passports', to='passport.passportsnapshot'),
        ),
        migrations.AddIndex(
            model_name='passportsnapshot',
            index=models.Index(fields=['passport', 'is_current'], name='passport_pa_passpor_88d479_idx'),
        ),
        migrations.AddConstraint(
            model_name='passportsnapshot',
            constraint=models.UniqueConstraint(fields=('passport', 'schema_version', 'source_fingerprint'), name='unique_passport_snapshot_input'),
        ),
        migrations.AddIndex(
            model_name='passportshare',
            index=models.Index(fields=['recipient_institution', 'status'], name='passport_pa_recipie_9a53cd_idx'),
        ),
        migrations.AddConstraint(
            model_name='passportsection',
            constraint=models.UniqueConstraint(fields=('snapshot', 'code'), name='unique_passport_section'),
        ),
        migrations.AddConstraint(
            model_name='financialpassport',
            constraint=models.UniqueConstraint(fields=('institution', 'customer'), name='unique_financial_passport_per_customer'),
        ),
    ]
