# Generated by Django 5.2.7 on 2026-09-17 15:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connector', '0001_initial'),
        ('normalisation', '0001_initial'),
        ('partner', '0003_credentialscope_partnerapplication_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_account_reference', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed')], db_index=True, default='ACTIVE', max_length=20)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_accounts', to='connector.institutionconnection')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_accounts', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_accounts', to='partner.institution')),
            ],
        ),
        migrations.CreateModel(
            name='LedgerPosting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('POSTED', 'Posted'), ('REVERSED', 'Reversed'), ('FAILED', 'Failed')], db_index=True, default='POSTED', max_length=20)),
                ('posted_at', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_postings', to='partner.institution')),
                ('reversal_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='ledger.ledgerposting')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_posting', to='normalisation.canonicaltransaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(max_length=3)),
                ('direction', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=10)),
                ('entry_type', models.CharField(choices=[('POSTING', 'Posting'), ('REVERSAL', 'Reversal'), ('CORRECTION', 'Correction')], default='POSTING', max_length=20)),
                ('effective_at', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='ledger.account')),
                ('compensates', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compensating_entries', to='ledger.ledgerentry')),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='ledger.ledgerposting')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReconciliationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('MISMATCHED', 'Mismatched')], db_index=True, default='RUNNING', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('matched_count', models.PositiveIntegerField(default=0)),
                ('mismatch_count', models.PositiveIntegerField(default=0)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_runs', to='connector.institutionconnection')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_runs', to='partner.institution')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReconciliationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_event_id', models.CharField(max_length=255)),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ledger_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('MATCHED', 'Matched'), ('MISMATCH', 'Mismatch'), ('UNRESOLVED', 'Unresolved')], db_index=True, default='UNRESOLVED', max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_items', to='normalisation.canonicaltransaction')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='ledger.reconciliationrun')),
            ],
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['institution', 'customer', 'status'], name='ledger_acco_institu_c13839_idx'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('institution', 'connection', 'source_account_reference', 'currency'), name='unique_ledger_account_source_reference'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationitem',
            constraint=models.UniqueConstraint(fields=('run', 'source_event_id'), name='unique_reconciliation_source_event'),
        ),
    ]
