# Generated by Django 5.2.7 on 2026-09-19 00:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRateSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_currency', models.CharField(max_length=3)),
                ('quote_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=10, max_digits=24)),
                ('source', models.CharField(max_length=100)),
                ('observed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['base_currency', 'quote_currency', '-observed_at'], name='ledger_exch_base_cu_dc6605_idx')],
                'constraints': [models.UniqueConstraint(fields=('base_currency', 'quote_currency', 'source', 'observed_at'), name='unique_exchange_rate_observation'), models.CheckConstraint(condition=models.Q(('rate__gt', 0)), name='exchange_rate_positive')],
            },
        ),
    ]
