# Generated by Django 5.2.7 on 2026-09-18 07:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feature', '0001_initial'),
        ('modeling', '0001_initial'),
        ('partner', '0003_credentialscope_partnerapplication_and_more'),
        ('rules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RiskEvaluationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_fingerprint', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='RUNNING', max_length=20)),
                ('failure_reason', models.CharField(blank=True, max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_evaluation_runs', to=settings.AUTH_USER_MODEL)),
                ('feature_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_evaluation_runs', to='feature.featurecomputationrun')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_evaluation_runs', to='partner.institution')),
                ('model_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_evaluation_runs', to='modeling.modelevaluationrun')),
                ('rule_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_evaluation_runs', to='rules.ruleevaluationrun')),
            ],
        ),
        migrations.CreateModel(
            name='RiskPolicyVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('RETIRED', 'Retired')], default='DRAFT', max_length=20)),
                ('configuration', models.JSONField(default=dict)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='risk.riskpolicy')),
            ],
        ),
        migrations.CreateModel(
            name='RiskEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(decimal_places=4, max_digits=9)),
                ('decision', models.CharField(choices=[('ALLOW', 'Allow'), ('CHALLENGE', 'Challenge'), ('HOLD', 'Hold'), ('BLOCK', 'Block')], max_length=20)),
                ('confidence', models.DecimalField(decimal_places=4, max_digits=5)),
                ('evaluated_at', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_events', to=settings.AUTH_USER_MODEL)),
                ('feature_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_events', to='feature.featurecomputationrun')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_events', to='partner.institution')),
                ('model_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_events', to='modeling.modelevaluationrun')),
                ('model_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_events', to='modeling.modelversion')),
                ('rule_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_events', to='rules.ruleevaluationrun')),
                ('ruleset_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_events', to='rules.rulesetversion')),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='event', to='risk.riskevaluationrun')),
                ('policy_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='risk.riskpolicyversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='riskevaluationrun',
            name='policy_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_runs', to='risk.riskpolicyversion'),
        ),
        migrations.CreateModel(
            name='RiskReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordinal', models.PositiveIntegerField(default=0)),
                ('code', models.CharField(max_length=100)),
                ('source', models.CharField(choices=[('RULE', 'Rule'), ('MODEL', 'Model'), ('POLICY', 'Policy'), ('EVIDENCE', 'Evidence')], max_length=20)),
                ('severity', models.CharField(blank=True, max_length=30)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reasons', to='risk.riskevent')),
            ],
            options={
                'ordering': ['ordinal'],
            },
        ),
        migrations.AddConstraint(
            model_name='riskpolicyversion',
            constraint=models.UniqueConstraint(fields=('policy', 'version'), name='unique_risk_policy_version'),
        ),
        migrations.AddConstraint(
            model_name='riskevaluationrun',
            constraint=models.UniqueConstraint(fields=('feature_run', 'rule_run', 'model_run', 'policy_version', 'source_fingerprint'), name='unique_risk_evaluation_input'),
        ),
    ]
