# Generated by Django 5.2.7 on 2026-09-18 13:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0001_initial'),
        ('modeling', '0001_initial'),
        ('partner', '0003_credentialscope_partnerapplication_and_more'),
        ('risk', '0001_initial'),
        ('rules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='riskevent',
            index=models.Index(fields=['institution', 'evaluated_at'], name='risk_riskev_institu_39b165_idx'),
        ),
    ]
