# Generated by Django 5.2.7 on 2026-09-18 13:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
        ('partner', '0003_credentialscope_partnerapplication_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['institution', 'opened_at'], name='case_case_institu_0ce816_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['institution', 'status'], name='case_case_institu_16e448_idx'),
        ),
    ]
