# Generated by Django 5.2.7 on 2026-09-18 15:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partner', '0003_credentialscope_partnerapplication_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialConfidencePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FinancialConfidencePolicyVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('RETIRED', 'Retired')], default='DRAFT', max_length=20)),
                ('configuration', models.JSONField(default=dict)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='confidence.financialconfidencepolicy')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialConfidenceSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_fingerprint', models.CharField(max_length=64)),
                ('score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('band', models.CharField(max_length=30)),
                ('completeness', models.DecimalField(decimal_places=4, max_digits=5)),
                ('provenance', models.JSONField(default=dict)),
                ('evaluated_at', models.DateTimeField()),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confidence_snapshots', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confidence_snapshots', to='partner.institution')),
                ('policy_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='confidence.financialconfidencepolicyversion')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialConfidenceComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=4, max_digits=5)),
                ('value', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('available', models.BooleanField(default=True)),
                ('unavailable_reason', models.CharField(blank=True, max_length=100)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='components', to='confidence.financialconfidencesnapshot')),
            ],
        ),
        migrations.AddConstraint(
            model_name='financialconfidencepolicyversion',
            constraint=models.UniqueConstraint(fields=('policy', 'version'), name='unique_confidence_policy_version'),
        ),
        migrations.AddIndex(
            model_name='financialconfidencesnapshot',
            index=models.Index(fields=['institution', 'customer', 'is_current'], name='confidence__institu_ef6559_idx'),
        ),
        migrations.AddConstraint(
            model_name='financialconfidencesnapshot',
            constraint=models.UniqueConstraint(fields=('institution', 'customer', 'policy_version', 'source_fingerprint'), name='unique_confidence_snapshot_input'),
        ),
        migrations.AddConstraint(
            model_name='financialconfidencecomponent',
            constraint=models.UniqueConstraint(fields=('snapshot', 'code'), name='unique_confidence_component'),
        ),
    ]
