# Generated by Django 5.2.7 on 2026-09-18 06:12

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partner', '0003_credentialscope_partnerapplication_and_more'),
        ('profile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('value_type', models.CharField(choices=[('DECIMAL', 'Decimal'), ('BOOLEAN', 'Boolean'), ('CATEGORICAL', 'Categorical')], max_length=20)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('version', models.CharField(default='1', max_length=50)),
                ('active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FeatureSetMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordinal', models.PositiveIntegerField(default=0)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='feature.featuredefinition')),
            ],
            options={
                'ordering': ['ordinal', 'definition__code'],
            },
        ),
        migrations.CreateModel(
            name='FeatureSetVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('RETIRED', 'Retired')], default='DRAFT', max_length=20)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('definitions', models.ManyToManyField(related_name='feature_sets', through='feature.FeatureSetMembership', to='feature.featuredefinition')),
            ],
        ),
        migrations.AddField(
            model_name='featuresetmembership',
            name='feature_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='feature.featuresetversion'),
        ),
        migrations.CreateModel(
            name='FeatureComputationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_fingerprint', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('REUSED', 'Reused'), ('FAILED', 'Failed')], default='RUNNING', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feature_computation_runs', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feature_computation_runs', to='partner.institution')),
                ('profile_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feature_runs', to='profile.financialprofilesnapshot')),
                ('feature_set_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='computation_runs', to='feature.featuresetversion')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('boolean_value', models.BooleanField(blank=True, null=True)),
                ('categorical_value', models.CharField(blank=True, max_length=100)),
                ('confidence', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=5)),
                ('available', models.BooleanField(default=True)),
                ('unavailable_reason', models.CharField(blank=True, max_length=100)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='feature.featuredefinition')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='feature.featurecomputationrun')),
            ],
        ),
        migrations.AddConstraint(
            model_name='featuresetversion',
            constraint=models.UniqueConstraint(fields=('code', 'version'), name='unique_feature_set_version'),
        ),
        migrations.AddConstraint(
            model_name='featuresetmembership',
            constraint=models.UniqueConstraint(fields=('feature_set', 'definition'), name='unique_feature_set_definition'),
        ),
        migrations.AddConstraint(
            model_name='featurecomputationrun',
            constraint=models.UniqueConstraint(fields=('profile_snapshot', 'feature_set_version', 'source_fingerprint'), name='unique_feature_computation_input'),
        ),
        migrations.AddConstraint(
            model_name='featurevalue',
            constraint=models.UniqueConstraint(fields=('run', 'definition'), name='unique_feature_value'),
        ),
    ]
