# Generated by Django 5.2.7 on 2026-09-18 15:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partner', '0003_credentialscope_partnerapplication_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_key', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=100)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='partner.institution')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('TRUSTED', 'Trusted'), ('SUSPICIOUS', 'Suspicious'), ('BLOCKED', 'Blocked')], default='UNKNOWN', max_length=20)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('observation_count', models.PositiveIntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_devices', to='partner.institution')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_links', to='security.device')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=100)),
                ('observed_at', models.DateTimeField()),
                ('provenance_type', models.CharField(max_length=100)),
                ('provenance_id', models.UUIDField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('customer_device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='security.customerdevice')),
            ],
            options={
                'ordering': ['observed_at'],
            },
        ),
        migrations.CreateModel(
            name='LocationObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=2)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('confidence', models.DecimalField(decimal_places=4, max_digits=5)),
                ('observed_at', models.DateTimeField()),
                ('provenance_type', models.CharField(max_length=100)),
                ('provenance_id', models.UUIDField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_observations', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_observations', to='partner.institution')),
            ],
            options={
                'ordering': ['observed_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('AUTHENTICATION_FAILURE', 'Authentication failure'), ('NEW_DEVICE', 'New device'), ('UNUSUAL_LOCATION', 'Unusual location'), ('CREDENTIAL_EVENT', 'Credential event'), ('CONSENT_SECURITY_EVENT', 'Consent security event'), ('ACCOUNT_ACCESS_ANOMALY', 'Account access anomaly')], max_length=30)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('source', models.CharField(max_length=100)),
                ('occurred_at', models.DateTimeField()),
                ('provenance_type', models.CharField(blank=True, max_length=100)),
                ('provenance_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='security_events', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='security_events', to='partner.institution')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('institution', 'device_key'), name='unique_device_per_institution'),
        ),
        migrations.AddIndex(
            model_name='customerdevice',
            index=models.Index(fields=['institution', 'customer'], name='security_cu_institu_a5a135_idx'),
        ),
        migrations.AddConstraint(
            model_name='customerdevice',
            constraint=models.UniqueConstraint(fields=('customer', 'device'), name='unique_customer_device'),
        ),
        migrations.AddConstraint(
            model_name='deviceobservation',
            constraint=models.UniqueConstraint(fields=('customer_device', 'provenance_type', 'provenance_id'), name='unique_device_observation'),
        ),
        migrations.AddConstraint(
            model_name='locationobservation',
            constraint=models.UniqueConstraint(fields=('customer', 'provenance_type', 'provenance_id'), name='unique_location_observation'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['institution', 'occurred_at'], name='security_se_institu_f5f2c0_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['customer', 'occurred_at'], name='security_se_custome_0eaed7_idx'),
        ),
    ]
