# Generated by Django 5.2.7 on 2026-09-18 12:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partner', '0003_credentialscope_partnerapplication_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphComputationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('graph_version', models.CharField(max_length=50)),
                ('source_fingerprint', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('REUSED', 'Reused'), ('FAILED', 'Failed')], default='RUNNING', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='graph_computation_runs', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='graph_computation_runs', to='partner.institution')),
            ],
        ),
        migrations.CreateModel(
            name='GraphEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edge_type', models.CharField(choices=[('CUSTOMER_OWNS_ACCOUNT', 'Customer owns account'), ('CUSTOMER_CONNECTED_TO_INSTITUTION', 'Customer connected to institution'), ('ACCOUNT_TRANSACTED_WITH_COUNTERPARTY', 'Account transacted with counterparty'), ('CASE_RELATES_TO_CUSTOMER', 'Case relates to customer'), ('CASE_RELATES_TO_RISK_EVENT', 'Case relates to risk event')], max_length=40)),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('first_occurred_at', models.DateTimeField()),
                ('last_occurred_at', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='graph_edges', to='partner.institution')),
            ],
        ),
        migrations.CreateModel(
            name='GraphEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provenance_type', models.CharField(max_length=100)),
                ('provenance_id', models.UUIDField()),
                ('observed_at', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('edge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='graph.graphedge')),
            ],
            options={
                'ordering': ['observed_at'],
            },
        ),
        migrations.CreateModel(
            name='GraphMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('available', models.BooleanField(default=True)),
                ('unavailable_reason', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metrics', to='graph.graphcomputationrun')),
            ],
        ),
        migrations.CreateModel(
            name='GraphNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node_type', models.CharField(choices=[('CUSTOMER', 'Customer'), ('INSTITUTION', 'Institution'), ('ACCOUNT', 'Account'), ('COUNTERPARTY', 'Counterparty'), ('CASE', 'Case'), ('RISK_EVENT', 'Risk event')], max_length=20)),
                ('natural_key', models.CharField(max_length=255)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='graph_nodes', to='partner.institution')),
            ],
        ),
        migrations.AddField(
            model_name='graphedge',
            name='source_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_edges', to='graph.graphnode'),
        ),
        migrations.AddField(
            model_name='graphedge',
            name='target_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_edges', to='graph.graphnode'),
        ),
        migrations.AddConstraint(
            model_name='graphcomputationrun',
            constraint=models.UniqueConstraint(fields=('institution', 'customer', 'graph_version', 'source_fingerprint'), name='unique_graph_computation_input'),
        ),
        migrations.AddConstraint(
            model_name='graphevidence',
            constraint=models.UniqueConstraint(fields=('edge', 'provenance_type', 'provenance_id'), name='unique_graph_evidence'),
        ),
        migrations.AddConstraint(
            model_name='graphmetric',
            constraint=models.UniqueConstraint(fields=('run', 'code'), name='unique_graph_metric'),
        ),
        migrations.AddIndex(
            model_name='graphnode',
            index=models.Index(fields=['institution', 'node_type'], name='graph_graph_institu_d4a975_idx'),
        ),
        migrations.AddConstraint(
            model_name='graphnode',
            constraint=models.UniqueConstraint(fields=('institution', 'node_type', 'natural_key'), name='unique_graph_node'),
        ),
        migrations.AddConstraint(
            model_name='graphedge',
            constraint=models.UniqueConstraint(fields=('institution', 'edge_type', 'source_node', 'target_node'), name='unique_graph_edge'),
        ),
    ]
